spring:
application:
name: calculo-implicito-odds
data:
mongodb:
uri: mongodb://localhost:27017/calculo_implicito
# Se estiver usando MongoDB Atlas depois, troque pela connection string

server:
port: 8080

# Opcional: logs mais claros
logging:
level:
org.springframework.data.mongodb: DEB